### NumPy: Введение (Часть 1) [Домашнее задание]

### Задания:

1. Установите пакет NumPy с помощью pip.

2. Пожалуйста, импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.19.5


### Ожидаемый результат
```
1.17.4
```

3. Создайте одномерный numpy.ndarray even_np, в котором он содержит четные числа только от 0 до 10.

In [4]:
# Начало вашего кода
even = [x for x in range(0, 11, 2)]
even_np = np.array(even)
# Конец вашего кода
print(even_np)

[ 0  2  4  6  8 10]


### Ожидаемый результат
```
[ 0  2  4  6  8 10]
```

4. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [5]:
# Начало вашего кода

# Число осей
print(f'even_np.ndim={even_np.ndim}')

# Длина массива по каждой оси
print(f'even_np.shape={even_np.shape}')

# Кол-во элементов массива
print(f'even_np.size={even_np.size}')

# Тип элементов масива
print(f'even_np.dtype={even_np.dtype}')

# Транспонирование массива
print(f'even_np.T={even_np.T}')
# Конец вашего кода

even_np.ndim=1
even_np.shape=(6,)
even_np.size=6
even_np.dtype=int64
even_np.T=[ 0  2  4  6  8 10]


### Ожидаемый результат
```
1
(6,)
6
int64
[ 0  2  4  6  8 10]
```

5. Создайте одномерный numpy.ndarray odd_np, в котором он содержит не четные числа только от 10 до 20, и тип элементов должен быть **комплексными числами.**

In [8]:
# Начало вашего кода
odd_np = np.array([x for x in range(11, 21, 2)], dtype = np.complex) 
# Конец вашего кода
print(odd_np)

[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


### Ожидаемый результат
```
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

6. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray odd_np и распечатайте их.

In [10]:
# Начало вашего кода
# Число осей
print(f'even_np.ndim={odd_np.ndim}')

# Длина массива по каждой оси
print(f'even_np.shape={odd_np.shape}')

# Кол-во элементов массива
print(f'even_np.size={odd_np.size}')

# Тип элементов масива
print(f'even_np.dtype={odd_np.dtype}')

# Транспонирование массива
print(f'even_np.T={odd_np.T}')
# Конец вашего кода

even_np.ndim=1
even_np.shape=(5,)
even_np.size=5
even_np.dtype=complex128
even_np.T=[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]


### Ожидаемый результат
```
1
(5,)
5
complex128
[11.+0.j 13.+0.j 15.+0.j 17.+0.j 19.+0.j]
```

# Прекрасная работа!