### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [62]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.19.5


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [63]:
# Начало вашего кода
numbers = np.array([[x for x in range(0,10,2)],[x for x in range(1,10,2)]])
# Конец вашего кода
print(numbers)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [64]:
# Начало вашего кода
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)
print(numbers.T)
# Конец вашего кода

2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [65]:
# Начало вашего кода
overall_max = numbers.max()
overall_min = numbers.min()
overall_mean = numbers.mean()
overall_std = numbers.std()
# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [66]:
# Начало вашего кода
col_max = numbers.max(axis=0, keepdims=True)
col_min = numbers.min(axis=0, keepdims=True)
col_mean = numbers.mean(axis=0, keepdims=True)
col_std = numbers.std(axis=0, keepdims=True)
# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [67]:
# Начало вашего кода
row_max = numbers.max(axis=1, keepdims=True)
row_min = numbers.min(axis=1, keepdims=True)
row_mean = numbers.mean(axis=1, keepdims=True)
row_std = numbers.std(axis=1, keepdims=True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [68]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
thd_nparr_max = thd_nparr.max()
thd_nparr_min = thd_nparr.min()
thd_nparr_mean = thd_nparr.mean()
thd_nparr_std = thd_nparr.std()
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [69]:
# Начало вашего кода
thd_nparr_mean_ax0 = thd_nparr.mean(axis=0, keepdims=True)
print(f'Mean with respect to 0-axis\n{thd_nparr_mean_ax0}')

thd_nparr_std_ax0 = thd_nparr.std(axis=0, keepdims=True)
print(f'STD with respect to 0-axis\n{thd_nparr_std_ax0}')

thd_nparr_mean_ax1 = thd_nparr.mean(axis=1, keepdims=True)
print(f'Mean with respect to 1-axis\n{thd_nparr_mean_ax1}')

thd_nparr_std_ax1 = thd_nparr.std(axis=1, keepdims=True)
print(f'STD with respect to 1-axis\n{thd_nparr_std_ax1}')

thd_nparr_mean_ax2 = thd_nparr.mean(axis=2, keepdims=True)
print(f'Mean with respect to 2-axis\n{thd_nparr_mean_ax2}')

thd_nparr_std_ax2 = thd_nparr.std(axis=2, keepdims=True)
print(f'STD with respect to 2-axis\n{thd_nparr_std_ax2}')

# Конец вашего кода

Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]
Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]
Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [70]:
# ndarray.reshape()
# Начало вашего кода
thd_nparr_reshape = thd_nparr.reshape(2,4)
print(thd_nparr_reshape)
# Конец вашего кода

[[ 1  2  3  4]
 [21 22 23 24]]


In [71]:
# ndarray.ravel()
# Начало вашего кода
print(thd_nparr.ravel())
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]


In [72]:
# ndarray.tolist()
# Начало вашего кода
print(thd_nparr.tolist())
# Конец вашего кода

[[[1, 2], [3, 4]], [[21, 22], [23, 24]]]


In [73]:
# ndarray.tofile()
# Начало вашего кода
thd_nparr.tofile("file.bin")
print(np.fromfile("file.bin",  dtype=np.int64))
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]


In [74]:
# ndarray.sort()
# Начало вашего кода
a = np.array([[2,7,1,8,90,11],[77,100,4000,6,45,19]])
print(a)
print('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-')
a.sort()
print(f'srot\n{a}')
print('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-')
b = np.array([[2,7,1,8,90,11],[77,100,4000,6,45,19]])
b.sort(axis=0)
print(f'sort/axis=0\n{b}')
print('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-')
c = np.array([[2,7,1,8,90,11],[77,100,4000,6,45,19]])
c.sort(axis=1)
print(f'sort/axis=1\n{c}')
# Конец вашего кода

[[   2    7    1    8   90   11]
 [  77  100 4000    6   45   19]]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
srot
[[   1    2    7    8   11   90]
 [   6   19   45   77  100 4000]]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
sort/axis=0
[[   2    7    1    6   45   11]
 [  77  100 4000    8   90   19]]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
sort/axis=1
[[   1    2    7    8   11   90]
 [   6   19   45   77  100 4000]]


In [75]:
# ndarray.transpose()
# Начало вашего кода
a = np.array([[2,7,1,8,90,11],[77,100,4000,6,45,19]])
print(a.transpose())
# Конец вашего кода

[[   2   77]
 [   7  100]
 [   1 4000]
 [   8    6]
 [  90   45]
 [  11   19]]


In [76]:
# ndarray.flatten()
# Начало вашего кода
a = np.array([[2,7,1,8,90,11],[77,100,4000,6,45,19]])
print(a.flatten())
# Конец вашего кода

[   2    7    1    8   90   11   77  100 4000    6   45   19]


In [77]:
# ndarray.argmin()
# Начало вашего кода
# Возвращает индекс мин знач по оси
z = np.array([[20,70,10,80,90,11],[717,11,4450,69,95,19],[1,50,2,7,202,33]])
print(z.argmin(axis=0))
# Конец вашего кода

[2 1 2 2 0 0]


In [78]:
# ndarray.argmax()
# Начало вашего кода
# Возвращает максим значение по оси
y = np.array([[20,70,10,80,90,11],[717,11,4450,69,95,19],[1,50,2,7,202,33]])
print(y.argmax(axis=1))
# Конец вашего кода

[4 2 4]


In [79]:
# ndarray.cumsum()
# Начало вашего кода
# складывает последовательно элемменты 
q = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(q.cumsum())
# Конец вашего кода

[ 1  3  6 10 15 21 28 36 45]


In [80]:
# ndarray.cumprod()
# Начало вашего кода
# Последовательное перемножение 
q = np.array([[1,2,3],[1,5,6],[7,8,9]])
print(q.cumprod())
# Конец вашего кода

[    1     2     6     6    30   180  1260 10080 90720]


In [81]:
# ndarray.dot()
# Начало вашего кода
# Умножение матрицы на число
print(q.dot(3))
# Конец вашего кода

[[ 3  6  9]
 [ 3 15 18]
 [21 24 27]]


In [103]:
# ndarray.squeeze()
# Начало вашего кода
h2 = np.array([[1,2,3,4,5]])
print(h2.squeeze(axis=0))
#print(h.squeeze(axis=-1))
# Конец вашего кода

[1 2 3 4 5]


In [109]:
# ndarray.repeat()
# Начало вашего кода
h = np.array([[[1,1,1],[2,2,2],[9,9,9]],[[7,7,7],[3,3,3],[4,4,4]],[[0,0,0],[5,5,5],[6,6,6]]])
print(h.repeat(5))
# Конец вашего кода

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 9 9 9 9 9 9 9
 9 9 9 9 9 9 9 9 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [ ]:
h = np.array([[[1,1,1],[2,2,2],[9,9,9]],[[7,7,7],[3,3,3],[4,4,4]],[[0,0,0],[5,5,5],[6,6,6]]])
print(h.shape)

# Прекрасная работа!