### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [1]:
import numpy as np

In [2]:
# numpy.zeros
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
# numpy.ones
print(np.ones((7,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [6]:
# numpy.full
print(np.full((4,4),5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
# numpy.eye
print(np.eye(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [19]:
# numpy.arange
print(np.arange(100,1000,15).reshape(5,12))

[[100 115 130 145 160 175 190 205 220 235 250 265]
 [280 295 310 325 340 355 370 385 400 415 430 445]
 [460 475 490 505 520 535 550 565 580 595 610 625]
 [640 655 670 685 700 715 730 745 760 775 790 805]
 [820 835 850 865 880 895 910 925 940 955 970 985]]


In [20]:
# numpy.add
a1 = np.array([[1,3,4],[-1,2,-6]])
a2 = np.array([[-1,-3,-4],[1,-2,6]])
print(np.add(a1,a2))

[[0 0 0]
 [0 0 0]]


In [21]:
# numpy.subtract
print(np.subtract(a1,a2))

[[  2   6   8]
 [ -2   4 -12]]


In [25]:
# numpy.sin
print(np.sin([30,60,90]))

[-0.98803162 -0.30481062  0.89399666]


In [26]:
# numpy.multiply
print(np.multiply(a1,a2))

[[ -1  -9 -16]
 [ -1  -4 -36]]


In [31]:
# numpy.sqrt
b1 = np.array([[16,4,9],[25,49,100]])
print(np.sqrt(b1))

[[ 4.  2.  3.]
 [ 5.  7. 10.]]


In [33]:
# numpy.dot
vector_a = np.array([[9,8,7],[7,6,5]])
vector_b = np.array([[3,5],[9,1],[7,2]])
print(np.dot(vector_a,vector_b))

[[148  67]
 [110  51]]


In [36]:
# numpy.sum
print(np.sum(a1)>np.sum(a2))

True


In [40]:
# numpy.zeros_like
z1 = np.full((2,2,2,2,2),7)
print(np.zeros_like(z1))

[[[[[0 0]
    [0 0]]

   [[0 0]
    [0 0]]]


  [[[0 0]
    [0 0]]

   [[0 0]
    [0 0]]]]



 [[[[0 0]
    [0 0]]

   [[0 0]
    [0 0]]]


  [[[0 0]
    [0 0]]

   [[0 0]
    [0 0]]]]]


In [43]:
# numpy.empty_like
print(np.empty_like(z1)==np.zeros_like(z1))

[[[[[ True  True]
    [ True  True]]

   [[ True  True]
    [ True  True]]]


  [[[ True  True]
    [ True  True]]

   [[ True  True]
    [ True  True]]]]



 [[[[ True  True]
    [ True  True]]

   [[ True  True]
    [ True  True]]]


  [[[ True  True]
    [ True  True]]

   [[ True  True]
    [ True  True]]]]]


In [45]:
# numpy.reshape
print(z1.reshape(4,4,2))

[[[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]
  [7 7]]]


In [60]:
# numpy.isnan
b = np.arange(20).reshape(5, 4)
print("\n",b)
print("\nIs NaN(Not a Number): \n", np.isnan(b))


 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Is NaN(Not a Number): 
 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [66]:
# numpy.random.sample
r = np.random.sample((2,3))
print(r)

[[0.90678498 0.89689496 0.93115304]
 [0.86702276 0.09772407 0.7243549 ]]


In [67]:
# numpy.random.random
r2 = np.random.random((4,5))
print(r2)

[[0.70007189 0.46923188 0.32869488 0.49641851 0.27362814]
 [0.58416321 0.04684443 0.39088813 0.3964689  0.23205456]
 [0.64888837 0.29921552 0.99316312 0.75048183 0.81799506]
 [0.67456185 0.20705313 0.62941319 0.21692764 0.17049954]]


In [73]:
# numpy.random.randint
r3 = np.random.randint(low=0, high=100, size=(4,4,4))
print(r3)

[[[90  6 99 61]
  [ 8 44  6 46]
  [ 3 43 87 16]
  [37 40  2 37]]

 [[60 80 81 73]
  [ 3 38 37 82]
  [11 75 72 10]
  [69 37  4  7]]

 [[87 48 50  2]
  [65 91 90 21]
  [99 20 97 23]
  [70 87 94  2]]

 [[11 14 18 70]
  [ 8  8  8 12]
  [15 85 79 50]
  [47 27 57 37]]]


In [75]:
# numpy.random.random_integers
r4 = np.random.random_integers(-100, 101, (2,3,4,2))
print(r4)

[[[[ 20 -17]
   [-55 -58]
   [ 15   3]
   [ 18   1]]

  [[ 59  97]
   [-19  79]
   [ 54 -32]
   [-76  68]]

  [[ 79  45]
   [ 64  48]
   [  9 -15]
   [-89 -15]]]


 [[[ 82  49]
   [-65  25]
   [-79  66]
   [-83   5]]

  [[ 85  82]
   [ 80  47]
   [ 61 -64]
   [-29 -93]]

  [[ 54   4]
   [-11 101]
   [-99  36]
   [ 75  -1]]]]
<ipython-input-75-e549fb20f7e0>:2: DeprecationWarning: This function is deprecated. Please call randint(-100, 101 + 1) instead
  r4 = np.random.random_integers(-100, 101, (2,3,4,2))


In [78]:
# numpy.random.uniform
g = np.random.uniform(2.1, 5.5, 10000)
print(g)

[5.01055683 5.24066627 2.2215395  ... 2.31945831 3.72713002 3.81481658]


In [102]:
# numpy.random.seed
for i in range(5):
    np.random.seed(i)
    print(np.random.randint(1, 1000))  

685
38
169
875
123


In [109]:
# numpy.random.shuffle
f = np.arange(10)
print(f)
np.random.shuffle(f) 
print(f)

[0 1 2 3 4 5 6 7 8 9]
[1 6 8 7 5 3 2 4 0 9]


In [113]:
# numpy.random.permutation
print(np.random.permutation(10))

[2 6 3 9 5 1 0 7 4 8]


In [126]:
# numpy.random.choice
f2 = np.arange(10)
print(np.random.choice(f2))

6


# Прекрасная работа!