# Пожалуйста, выполните задачи ниже.

Вам может понадобиться больше узнать о методах, предоставляемых пакетом Numpy.

1. Создайте числовые массивы формы ```(20,5)``` со случайно сгенерированными целыми числами от 1 до 1000 (```numpy.random```). Установите ```seed=1```.

In [24]:
# Начало вашего кода
import numpy as np

np.random.seed(1)
np_arr_rand = np.random.randint(low=1,high=1000,size=(20,5))
print(np_arr_rand)
# Конец вашего кода


[[ 38 236 909  73 768]
 [906 716 646 848 961]
 [145 130 973 584 750]
 [509 391 282 179 277]
 [255 358 915 469 908]
 [253 491 669 926 399]
 [563 581 216 984 754]
 [504 479 865  87 142]
 [394   8 320 830 535]
 [314 514 897 317 210]
 [265 729 654 628 432]
 [634 457 543  72 388]
 [455 918 562 314 516]
 [965 793 498  44 589]
 [ 27 821 337 622 884]
 [298 467  16  65 197]
 [ 26 368 739 472 904]
 [283 666 617  23 778]
 [708 127 280 382 357]
 [156 934 314 596 167]]


### Ожидаемый результат:

```
[[ 38 236 909  73 768]
 [906 716 646 848 961]
 [145 130 973 584 750]
 [509 391 282 179 277]
 [255 358 915 469 908]
 [253 491 669 926 399]
 [563 581 216 984 754]
 [504 479 865  87 142]
 [394   8 320 830 535]
 [314 514 897 317 210]
 [265 729 654 628 432]
 [634 457 543  72 388]
 [455 918 562 314 516]
 [965 793 498  44 589]
 [ 27 821 337 622 884]
 [298 467  16  65 197]
 [ 26 368 739 472 904]
 [283 666 617  23 778]
 [708 127 280 382 357]
 [156 934 314 596 167]]
```

2. Каково среднее значение третьего столбца?

In [25]:
# Начало вашего кода
print(np.mean(np_arr_rand, axis=0)[2])
# Конец вашего кода

562.6


### Ожидаемый результат:

```
562.6
```

3. Каково среднее значение последних 5 строк второго и третьего столбцов?

In [26]:
# Начало вашего кода
print(np.mean(np_arr_rand[15:20,2:4]))
# Конец вашего кода

350.4


### Ожидаемый результат:

```
350.4
```

4. Выберите числа из последнего столбца массива, которые больше 300 и меньше, чем 500.

In [27]:
# Начало вашего кода
ar = np_arr_rand[:,4:]
bool_ar = ar>300
ar2 = ar[bool_ar]
bool_ar2 = ar2<500
print(ar2[bool_ar2])
# Конец вашего кода

[399 432 388 357]


### Ожидаемый результат:

```
[399 432 388 357]
```

5. Напишите функцию, которая проверяет, равен ли какой-либо из элементов данного массива numpy нулю.

In [28]:
arr = np_arr_rand
def check_zeros(input_arr):
    # Начало вашего кода
    return np.any(input_arr==0)
    # Конец вашего кода
print(check_zeros(arr))

False


### Ожидаемый результат:

```
False
```

6. Пожалуйста, сгенерируйте массив из пяти случайных чисел из равномерного распределения.

In [29]:
# Начало вашего кода
np.random.seed(1)
arr_norm = np.random.randn(5)
arr_norm2 = np.random.uniform(low=0, high=100, size=5)
# Конец вашего кода
print(arr_norm)
print(arr_norm2)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
[41.91945144 68.52195004 20.44522497 87.81174364  2.73875932]


### Ожидаемый результат:

```
[0.21162812 0.26554666 0.49157316 0.05336255 0.57411761]
```

7. Пожалуйста, сгенерируйте массив случайных чисел формы 3х3х4 из равномерного распределения.

In [30]:
# Начало вашего кода
arr3d = np.random.uniform(low=0, high=1, size=(3,3,4))
# Конец вашего кода
print(arr3d)

[[[0.67046751 0.4173048  0.55868983 0.14038694]
  [0.19810149 0.80074457 0.96826158 0.31342418]
  [0.69232262 0.87638915 0.89460666 0.08504421]]

 [[0.03905478 0.16983042 0.8781425  0.09834683]
  [0.42110763 0.95788953 0.53316528 0.69187711]
  [0.31551563 0.68650093 0.83462567 0.01828828]]

 [[0.75014431 0.98886109 0.74816565 0.28044399]
  [0.78927933 0.10322601 0.44789353 0.9085955 ]
  [0.29361415 0.28777534 0.13002857 0.01936696]]]


### Ожидаемый результат:

```
[[[0.14672857 0.58930554 0.69975836 0.10233443]
  [0.41405599 0.69440016 0.41417927 0.04995346]
  [0.53589641 0.66379465 0.51488911 0.94459476]]

 [[0.58655504 0.90340192 0.1374747  0.13927635]
  [0.80739129 0.39767684 0.1653542  0.92750858]
  [0.34776586 0.7508121  0.72599799 0.88330609]]

 [[0.62367221 0.75094243 0.34889834 0.26992789]
  [0.89588622 0.42809119 0.96484005 0.6634415 ]
  [0.62169572 0.11474597 0.94948926 0.44991213]]]
```

8. Пожалуйста, сгенерируйте массив случайных чисел формы 5х5 из равномерного распределения и найдите минимальное и максимальное значения.

In [31]:
# Начало вашего кода
arr2d = np.random.uniform(size=(5,5))
min_val = np.min(arr2d)
max_val = np.max(arr2d)
# Конец вашего кода
print(arr2d)
print(min_val)
print(max_val)

[[0.67883553 0.21162812 0.26554666 0.49157316 0.05336255]
 [0.57411761 0.14672857 0.58930554 0.69975836 0.10233443]
 [0.41405599 0.69440016 0.41417927 0.04995346 0.53589641]
 [0.66379465 0.51488911 0.94459476 0.58655504 0.90340192]
 [0.1374747  0.13927635 0.80739129 0.39767684 0.1653542 ]]
0.04995345894608716
0.9445947559908133


### Ожидаемый результат:

```
[[0.57838961 0.4081368  0.23702698 0.90337952 0.57367949]
 [0.00287033 0.61714491 0.3266449  0.5270581  0.8859421 ]
 [0.35726976 0.90853515 0.62336012 0.01582124 0.92943723]
 [0.69089692 0.99732285 0.17234051 0.13713575 0.93259546]
 [0.69681816 0.06600017 0.75546305 0.75387619 0.92302454]]
0.00287032703115897
0.9973228504514805
```

9. Пожалуйста, перетасуйте (```np.random```) цифры от 0 до 10 (включительно) 

In [32]:
# Начало вашего кода
arr_shuf = np.random.randint(low=0, high=11, size=10)
np.random.shuffle(arr_shuf)
# Конец вашего кода
print(arr_shuf)

[ 2  0  1 10  7  9  9  4  0  7]


### Ожидаемый результат:

```
[10  3  6  1  0  4  8  5  7  2  9]
```

10. Пожалуйста, создайте массив (10,) случайных чисел и отсортируйте его

In [33]:
# Начало вашего кода
arr_sort = np.random.uniform(size=10)
arr_sort.sort()
# Конец вашего кода
print(arr_sort)

[0.06406733 0.07379201 0.3013605  0.35531036 0.37980329 0.49810907
 0.76292007 0.771595   0.78695147 0.94183695]


### Ожидаемый результат:

```
[0.09155644 0.10213523 0.23175846 0.23362252 0.27831884 0.28871783
 0.36784324 0.41792654 0.57006666 0.96766793]
```

### Пожалуйста, найдите все ошибки в коде и исправьте.

Помните, что блок кодов может содержать более 1 ошибки.

11. Ожидаемый результат:

```
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]
```

In [34]:
print(np.linspace(0,21,21, endpoint=False))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]


12. Ожидаемый результат:

```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
```

In [35]:
print(np.arange(0,100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


13. Ожидаемый результат:

```
[[[[0.14672857 0.58930554 0.69975836]
   [0.10233443 0.41405599 0.69440016]]

  [[0.41417927 0.04995346 0.53589641]
   [0.66379465 0.51488911 0.94459476]]

  [[0.58655504 0.90340192 0.1374747 ]
   [0.13927635 0.80739129 0.39767684]]]


 [[[0.1653542  0.92750858 0.34776586]
   [0.7508121  0.72599799 0.88330609]]

  [[0.62367221 0.75094243 0.34889834]
   [0.26992789 0.89588622 0.42809119]]

  [[0.96484005 0.6634415  0.62169572]
   [0.11474597 0.94948926 0.44991213]]]]
```

In [43]:
print(np.resize(arr3d,(3,2,3,-1)))

[[[[0.67046751]
   [0.4173048 ]
   [0.55868983]]

  [[0.14038694]
   [0.19810149]
   [0.80074457]]]


 [[[0.96826158]
   [0.31342418]
   [0.69232262]]

  [[0.87638915]
   [0.89460666]
   [0.08504421]]]


 [[[0.03905478]
   [0.16983042]
   [0.8781425 ]]

  [[0.09834683]
   [0.42110763]
   [0.95788953]]]]


14. Ожидаемый результат:

``` 
[32. 19. 25. 21. 26. 18. 22. 27. 37. 14.]

```

In [37]:
np.random.seed(2)
arr1=np.ones(5)
arr2=np.integers(low=0,high=10,size=(10,5))
print(arr2*arr1)

AttributeError: module 'numpy' has no attribute 'integers'

15. Ожидаемый результат:

``` 
[[2.32624478 2.99713989 2.11483556 2.3372708  4.24467882]]

```

In [ ]:
arr1=arr1.reshape(-1,1)
print(arr1.dot(arr2d))

# Прекрасная работа!