### NumPy: Индексы & Срезы [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [1]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.19.5


### Ожидаемый результат
```
1.17.4
```

2. Вам предоставляется список ```list1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]```.
Пожалуйста, извлеките элементы списка ```list1```, который разделяет его индекс в списке ```list1``` без остатка. Используйте два подхода для решения этой проблемы, используя только список ```list``` и используя массив ```numpy.ndarray``` отдельно.

    **Примечание: не используйте ```enumerate```.**

In [2]:
list1 = [1,3,5,2,3,5,72,4,7,4,2,6,5,4,89,9,6,423]
list2 = []

# list
# Начало вашего кода
list2.extend(list1[0:11:5])
# Конец вашего кода
print(list2)

[1, 5, 2]


### Ожидаемый результат
```
[1, 5, 2]
```

In [3]:
# numpy.ndarray
# Начало вашего кода
ndarr1 = np.array(list1)
ndarr2 = ndarr1[0:11:5]
# Конец вашего кода
print(ndarr2)

[1 5 2]


### Ожидаемый результат
```
[1 5 2]
```

3. Вам предоставляется список списков ```list_of_lists=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]```. Пожалуйста, извлеките элементы, которые делят произведение индекса строки и индекса столбца без остатка.Используйте два подхода для решения этой проблемы, используя только список list и используя массив numpy.ndarray отдельно.

**Примечание: не используйте ```enumerate```.**

In [4]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
new_list = []

# list
# Начало вашего кода
for i in list_of_lists:
    idx_i = list_of_lists.index(i)
    for j in i:
        idx_j = i.index(j)
        if (idx_i * idx_j)%j == 0:
            new_list.append(j)
# Конец вашего кода
print(new_list)

[1, 2, 3, 4, 5, 9]


### Ожидаемый результат
```
[1, 2, 3, 4, 5, 9]
```

In [5]:
# numpy.ndarray
# Начало вашего кода
new_list = np.array(list_of_lists)
if len(new_list.shape)==2:
    w=new_list.shape[0]
    h=new_list.shape[1]
 
new = []
for x in range(w):
    for y in range(h):
        if (y*x)%new_list[x,y] == 0:
            new.append(new_list[x,y])
ndarr3 = np.array(new)

# Конец вашего кода
print(ndarr3)

[1 2 3 4 5 9]


### Ожидаемый результат
```
[1 2 3 4 5 9]
```

4. Пожалуйста, напишите две функции:

```slice_list(orig_list, row_str, row_end, col_str, col_end)```

```slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end)```


row_str и row_end - начальный индекс столбца и конечный индекс столбца среза.

col_str и col_end - начальный индекс столбца и конечный индекс столбца среза.

Пример:
```
orig_list =[[ 1, 2, 3],
            [11,12,13],
            [21,22,23]]

res_list = slice_list(orig_list, 0, 2, 1, 3)

Ответ:
res_list = [[ 2, 3],
            [12,13]]

```

In [6]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

def slice_list(orig_list, row_str, row_end, col_str, col_end):
    # list
    # Начало вашего кода
    new = []
    for i in orig_list[row_str:row_end]:
        new.append(i[col_str:col_end])
    return new
    # Конец вашего кода

print(slice_list(list_of_lists,1,4,1,3))

[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

In [7]:
list_of_lists = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]

def slice_list_ndarr(orig_list, row_str, row_end, col_str, col_end):
    # numpy.ndarray
    # Начало вашего кода
    nporing_list = np.array(orig_list)
    return nporing_list[row_str:row_end, col_str:col_end].tolist()
    # Конец вашего кода

print(slice_list_ndarr(list_of_lists,1,4,1,3))

[[6, 7], [10, 11], [14, 15]]


### Ожидаемый результат
```
[[6, 7], [10, 11], [14, 15]]
```

# Прекрасная работа!